name: CI
on:
  push:
    branches: [ master ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: echo action name
        run: echo ${{ github.event_name }}
      - name: echo tag name
        run: echo ${{ github.ref_name }}

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}          # The AWS access key ID in GitHub Secrets Manager
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # The AWS secret access key in GitHub Secrets Manager
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, And Push Backend Image To Amazon ECR
        if: github.ref_name != 'master'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: machine
          IMAGE_TAG: latest
        run: |
          echo "Building Backend image..."
          echo "ECR_REGISTRY: ${{ env.ECR_REGISTRY }}"
          echo "ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}"
          echo "IMAGE_TAG: ${{ env.IMAGE_TAG }}"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:${{github.ref_name}} -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags    
