name: Build Image - Environment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
jobs:
  build:
    runs-on: ubuntu-latest
    environment: "${{ github.event.inputs.environment }}"
    steps:
      - uses: actions/checkout@v3

      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        env:
          IMAGE_TAG: ${{ vars.IMAGE_TAG }}
        with:
          image: arwanashaat/$IMAGE_TAG
          tags: v3, latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}