name: Build Docker File
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: |
          cd /home/runner/work/build-a-docker-image-github-action/build-a-docker-image-github-action
          docker build -t dummay-app:1.0 -f ./DockerFile .
