name: Build Image - Choices
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Choose Environment
        options:
          - Testing
          - Staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get specified property
        id: repository_type
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: 'environments-name.json'
          prop_path: "${{ github.event.inputs.name }}.IMAGE_TAG"
      - run: echo ${{steps.repository_type.outputs.value}}

      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        env:
          IMAGE_TAG: ${{steps.repository_type.outputs.value}}
        with:
          image: arwanashaat/$IMAGE_TAG
          tags: v5, latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}